name: helper
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_datetime_picker: ^1.5.0
  intl: ^0.16.1
  geocoder: ^0.2.1
  geolocator: ^5.3.2+2
  cloud_firestore: ^0.13.5
  firebase_auth: ^0.16.1
  firebase_core: ^0.4.0
  flutter_spinkit: "^4.1.2"
  image_picker: ^0.6.7+22
  path: ^1.7.0
  firebase_storage: ^3.1.6
  transparent_image: ^1.0.0
  shared_preferences: ^0.5.12


  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - images/proffession.png
      - images/bg.png
      - images/bg1.png
      - images/bg2.png
      - images/Logo.png
      - images/carpentry.png
      - images/electrical.png
      - images/backgraound.png
      - images/AirCondition.png
      - images/grass.png
      - images/painting.png
      - images/plumbing.png
      - images/electronics.png
      - images/house.png
      - images/other.png
      - images/puzzle.png
      - images/tools-and-utensils.png
      - images/farmer.png
      - images/pro.png
      - images/speaker.jpg
      - images/profilePicture.png
      - images/clock.png 
      - images/houses.png
      - images/done.png
      - images/orderconfirm.png
      - images/user.png
      - images/Worker.png
      - images/box.png
      - images/boxs.png
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: YuseiMagic
      fonts:
        - asset: fonts/YuseiMagic-Regular.ttf
        
    - family: PTSansNarrow-Regular
      fonts:
        - asset: fonts/PTSansNarrow-Regular.ttf